### ISSUE TITLE
error: no such file or directory - Node 6 - solution in comments

### ISSUE THREAD

**Issue by hatemhosny** [NathanWalker/template-nativescript-nx#1]
Hi,

I followed [this tutorial](https://egghead.io/lessons/angular-set-up-a-nativescript-app-in-an-nx-workspace). 

on executing:

`/d/DevWork/nxdemo/apps $ tns create mobile --template https://github.com/NathanWalker/template-nativescript-nx`

I get the following error:

```
Support for Node.js 8.4.0 is not verified. This CLI might not install or run properly.

Installing https://github.com/NathanWalker/template-nativescript-nx 
Preparing NativeScript for Nx... 
Cleaning up... 
NativeScript for Nx is finalizing...

nativescript-nx@1.0.0 added 3 packages in 7.818s
cp: no such file or directory: D:\DevWork\nxdemo\apps\mobile\node_modules@angular\animations*
```
can you please guide? 
thanks

**Comment by hatemhosny** [comment]
I have modified [`tools/postintall.js #L47`](https://github.com/NathanWalker/template-nativescript-nx/blob/05443e8d2d9c4a8b7b1a801cb9e669e28fffae81/tools/postinstall.js#L47)
from
`exec("cd .. && npm prefix", (err, stdout) => {`
to
`exec("npm prefix", (err, stdout) => {`

and now it installs successfully.

but when I run `tns run android --emulator`
I get this error in the emulator
```
TypeError: core_1.OpaqueToken is not a contructor
File: "file:///data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-ngx-fonticon/src/app/services/fonticon.service.js, line: 9, column: 20
```

Nx currently uses angular 5 by default. is that related?

thanks

**Comment by hatemhosny** [comment]
It is related to angular version.

changed Nx angular version to 4.4.4 and now it works.

It would be great if you can upgrade this repo to angular 5

Thanks a lot

**Comment by marcelmaatkamp** [comment]
I have made a new issue #2: "please upgrade to angular5" to address the real issue

**Comment by NathanWalker** [comment]
Hi @hatemhosny and @marcelmaatkamp the template is now updated to work with latest Nx using Angular 5.
Please let me know if you ever further issue. 👍

**Comment by hatemhosny** [comment]
Thank you @NathanWalker 

I still have to remove `cd ..` from [`tools/postintall.js #L47`](https://github.com/NathanWalker/template-nativescript-nx/blob/05443e8d2d9c4a8b7b1a801cb9e669e28fffae81/tools/postinstall.js#L47)

I tried in on windows 10, node 6.10.3

but otherwise, it works very well :)

Thank you for sharing this.

**Comment by NathanWalker** [comment]
Hmm @hatemhosny I'm guessing that's a Windows only issue? I could add a platform hook there, I'll investigate that at some point. I'm going to rename this issue to state Windows so others whom may encounter that might find it here in the issues.

**Comment by hatemhosny** [comment]
Hi @NathanWalker 
I think it is an issue related to npm

Now it works fine, after I switched to node 8.9.1 with npm 5.5.1 (using nvm).
it did not work on node 6.10.3 with npm 3.10.10
I'm still on windows 10

I hope this helps
