### ISSUE TITLE
How to import from npmScope ? 

### ISSUE THREAD

**Issue by eloyleonardo** [NathanWalker/template-nativescript-nx#10]
This can be a silly question, but i can't find anywhere.

How can i import a module or a service from the scope. Like:

The autocomplete generate this: And the compiler give the follow error: JS ERROR Error: Could not find module 
``
import {CoreModule} from '../../../libs/core';
``

The right path doesn't should be like:

``
import {CoreModule} from '@my-worskapce/libs/core';
``

how can i map the npmScope @my-worskapce to the nativescript app ?

**Comment by m-abs** [comment]
I asked the same, see Nathan's reply here:
https://github.com/NathanWalker/template-nativescript-nx/issues/3#issuecomment-355473852

**Comment by NathanWalker** [comment]
You’ll want to create a package.json in each lib sub folder and then you can install each lib into the NativeScript project like any other dependency, ie from root of the apps/mobile (or whatever you named the app) directory:
```
npm i ../../libs/core 
```
Then you can import from the namespace as indicated in the lib package.json name property.

**Comment by eloyleonardo** [comment]
Thank you @m-abs  and @NathanWalker.
And sorry for the duplicate issue, i didn't saw that issue.

**Comment by eloyleonardo** [comment]
I need to manually compile the library ?
I follow what you said and when i run the nativescript app it give me the error: JS ERROR Error: Could not find module './src/service'. And in the library i just cant see the .js of the index.ts.

How this works ?
And sorry for one more dummy question

**Comment by NathanWalker** [comment]
Open apps/mobile/tsconfig.json and add ‘../../libs/core/index.ts’ to the ‘includes’ array.

**Comment by eloyleonardo** [comment]
Woks like a charm.

Thankyou @NathanWalker
