### ISSUE TITLE
Generating new modules crawls apps/mobile/platform folder

### ISSUE THREAD

**Issue by m-abs** [NathanWalker/template-nativescript-nx#12]
Hi,

When I create a new module with the cli, it spends a lot of time crawling apps/mobile/platforms folder.

I ran the command:
```bash
ng g newModuleName --ngmodule
```

After which all the *.ts files from the platforms folder was listed, this took about two minutes.

Is there a way to prevent the ng-cli from crawling the platform-folder?

**Comment by NathanWalker** [comment]
Thanks for heads up. I’ll look into this as I’m working on schematics around this.

**Comment by m-abs** [comment]
More info.

It's caused by the `nx format` job.
`node_modules/@nrwl/schematics/src/command-line/format.js` line 36 creates the pattern 
```typescript
['"{apps,libs}/**/*.ts"']
```

Which of cause matches everything under `apps/mobile/platforms`...

**Comment by m-abs** [comment]
I got tired of it and made this very dirty workaround: https://gist.github.com/m-abs/7143d2b598091c577a57f6d0fe8948c8

**Comment by NathanWalker** [comment]
Thanks @m-abs good workaround for now - I'll work this into the schematic to make a little more seamless. 👍 Hope to have them out sometime next week.
