### ISSUE TITLE
How to start the mobile app?

### ISSUE THREAD

**Issue by bumpety** [NathanWalker/template-nativescript-nx#13]
Hi, I tried for a couple of hours to get it working, but I have no idea how to run the npm commands inside the nativescript app from root. If I am inside the nativescript app dir I try npm run start-android-bundle and get this error: 

"Using npm run scripts is no longer supported. Use CLI commands and pass the --bundle flag instead."

**Comment by m-abs** [comment]
Use "tns run android --bundle"

**Comment by bumpety** [comment]
Thanks a lot. I just read it in the nativescript doc. *shame on me*
