### ISSUE TITLE
Angular 6 compatible

### ISSUE THREAD

**Issue by nartc** [NathanWalker/template-nativescript-nx#14]
Nx now creates Angular apps with version 6 by default and this template links Angular 5's packages with NativeScript-Angular. Is there a possible update to this template?

**Comment by NathanWalker** [comment]
Hi @nartc I wouldn’t recommend using this template any longer since we have rolled all this into xplat. Give this a try instead:
https://nstudio.io/xplat/

Lemme know if you have any trouble.

**Comment by nartc** [comment]
Thank you @NathanWalker .

Closed!
