### ISSUE TITLE
Can't install on a clean Nx workspace

### ISSUE THREAD

**Issue by VladimirMakaev** [NathanWalker/template-nativescript-nx#4]
When running  
tns create test-mobile --templatehttps://github.com/NathanWalker/template-nativescript-nx

I'm getting the following:

```
Installing  https://github.com/NathanWalker/template-nativescript-nx
1. Preparing NativeScript for Nx.
2. Cleaning up.
3. NativeScript for Nx is finalizing...
+ nativescript-nx@1.0.0
added 3 packages in 2.9s
cp: no such file or directory: /Users/vladimir/Projects/Test/apps/test-mobile/node_modules/https:/github.com/NathanWalker/template-nativescript-nx/*
```
Node: 8.7.0
OS: MacOS High Sierra 10.13.1

**Comment by m-abs** [comment]
Works for me, if I add the space between --template and https

**Comment by VladimirMakaev** [comment]
I can't believe I missed the space there :). Probably it was a word wrapping in terminal. It works now!
