### ISSUE TITLE
Support for shared modules between NativeScript and Web

### ISSUE THREAD

**Issue by VladimirMakaev** [NathanWalker/template-nativescript-nx#5]
One of the recommended way to build shared modules between NativeScript and Web is to use build time solution with conditionally using `moduleName.module.tns.ts` for NativeScript and `moduleName.module.ts` for web.

This is particularly needed in the scenarios when we share commonly used set of UI Components. E.g. we might wanna have a unified layer of components like: my-datepicker, my-button, my-table which are implemented by e.g. ng-semantic on web and hand coded for NativeScript but they have the same data contract and therefore other vertical cross platform feature modules can import them consistently on both platforms. I can only think of that build time solution to support AOT compilation.

Same approach is used by this seed project https://github.com/TeamMaestro/angular-native-seed

Do you have any plans to support this scenario? Pottentially be able to generate shared module using cli?

**Comment by m-abs** [comment]
I don't think that would fit very well with the way nx works.

Nathan posted a suggestion on the angular-seed-advanced project, that I think would be more fitting:
https://github.com/NathanWalker/angular-seed-advanced/issues/474

**Comment by VladimirMakaev** [comment]
I see.. Basically that basically leeds to a desing like that:

![angular - multiplatform angular](https://user-images.githubusercontent.com/2001475/33400281-72a5bdd2-d54d-11e7-88f0-e215e228b47a.jpg)

Which might be just ok.  Thanks for pointing me out to that issue.
